# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from minknow_api import notifications_pb2 as minknow__api_dot_notifications__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in minknow_api/notifications_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NotificationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stream_notifications = channel.unary_stream(
                '/minknow_api.notifications.NotificationsService/stream_notifications',
                request_serializer=minknow__api_dot_notifications__pb2.StreamNotificationsRequest.SerializeToString,
                response_deserializer=minknow__api_dot_notifications__pb2.StreamNotificationsResponse.FromString,
                _registered_method=True)
        self.mark_notifications_as_read = channel.unary_unary(
                '/minknow_api.notifications.NotificationsService/mark_notifications_as_read',
                request_serializer=minknow__api_dot_notifications__pb2.MarkNotificationsAsReadRequest.SerializeToString,
                response_deserializer=minknow__api_dot_notifications__pb2.MarkNotificationsAsReadResponse.FromString,
                _registered_method=True)
        self.create_notification = channel.unary_unary(
                '/minknow_api.notifications.NotificationsService/create_notification',
                request_serializer=minknow__api_dot_notifications__pb2.CreateNotificationRequest.SerializeToString,
                response_deserializer=minknow__api_dot_notifications__pb2.CreateNotificationResponse.FromString,
                _registered_method=True)


class NotificationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stream_notifications(self, request, context):
        """Sends an initial list of all historical notifications and sends any new notifications as they are
        created or, optionally, updated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mark_notifications_as_read(self, request, context):
        """Mark existing notifications as `read`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_notification(self, request, context):
        """Create a new notification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stream_notifications': grpc.unary_stream_rpc_method_handler(
                    servicer.stream_notifications,
                    request_deserializer=minknow__api_dot_notifications__pb2.StreamNotificationsRequest.FromString,
                    response_serializer=minknow__api_dot_notifications__pb2.StreamNotificationsResponse.SerializeToString,
            ),
            'mark_notifications_as_read': grpc.unary_unary_rpc_method_handler(
                    servicer.mark_notifications_as_read,
                    request_deserializer=minknow__api_dot_notifications__pb2.MarkNotificationsAsReadRequest.FromString,
                    response_serializer=minknow__api_dot_notifications__pb2.MarkNotificationsAsReadResponse.SerializeToString,
            ),
            'create_notification': grpc.unary_unary_rpc_method_handler(
                    servicer.create_notification,
                    request_deserializer=minknow__api_dot_notifications__pb2.CreateNotificationRequest.FromString,
                    response_serializer=minknow__api_dot_notifications__pb2.CreateNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minknow_api.notifications.NotificationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stream_notifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/minknow_api.notifications.NotificationsService/stream_notifications',
            minknow__api_dot_notifications__pb2.StreamNotificationsRequest.SerializeToString,
            minknow__api_dot_notifications__pb2.StreamNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def mark_notifications_as_read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minknow_api.notifications.NotificationsService/mark_notifications_as_read',
            minknow__api_dot_notifications__pb2.MarkNotificationsAsReadRequest.SerializeToString,
            minknow__api_dot_notifications__pb2.MarkNotificationsAsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_notification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minknow_api.notifications.NotificationsService/create_notification',
            minknow__api_dot_notifications__pb2.CreateNotificationRequest.SerializeToString,
            minknow__api_dot_notifications__pb2.CreateNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
