name: Build Debian Package

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x create_deb_package.sh

      - name: Build .deb Package
        run: ./create_deb_package.sh

      - name: Upload .deb to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.deb"
      
      - name: Upload .deb as Artifact (Manual Trigger)
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: minknow-dashboard-deb
          path: "*.deb"
